### ISSUE TITLE
Debian target architecture x86_64 instead of required amd64

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/epm#33]
Version: 4.2
Original reporter: 

Packages build on Debian (64 bit) hold within them the target architecture x86_64.  The Debian dpkg will refuse to install these packages, since it expects the same architecture as provided by `dpkg --print-architecture`, which on my host is 'amd64'.

Tested with the EPM 4.2 just downloaded from epmhome.org on an up-to-date Debian 6 (the Debian package for EPM was removed for this test).

This bug is reported (incorrectly IMHO) as fixed by the package maintainer at Debian:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=573433

To reproduce the problem I used the file list dummy.epm:

%product Dummy
%copyright 2011 by Nobody, All Rights Released.
%vendor Nobody
%license EMPTY
%readme EMPTY
%description An empty package for testing EPM
%version 1.0 100

f 666 root root /tmp EMPTY

The file EMPTY is indeed an empty file.

The package was build with:

fakeroot epm -f native --output-dir outcome dummy dummy.epm

The resulting package is called dummy-1.0-linux-2.6-x86_64.deb, which gdebi complains as having the wrong architecture 'x86_64'.

The workaround is to build the package with:

fakeroot epm -f native -a amd64 --output-dir outcome dummy dummy.epm

However, this forces calling scripts to be specifically written for  Debian.

**Comment by cpatrick08** [comment]
i have this same problem in Ubuntu 17.10 
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 4 package 'cups:x86_64':
 'x86_64' is not a valid architecture name: character '_' not allowed (only letters, digits and characters '-')
dpkg: error processing archive cups-2.2.5-linux-4.12-x86_64.deb (--install):
 package architecture (x86_64) does not match system (amd64)
