### ISSUE TITLE
Debian x86_64 vs amd64 bug redux

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/epm#48]
Version: 4.3
Original reporter: Rawiri Blundell

Hi,
I have a similar issue to Bug #295, except that it occurs when manually installing EPM from source.

`./configure` and `make` succeed, however here's the output of `make test`

# make test
Starting portable distribution build test...
Portable distribution build test PASSED.
Starting native distribution build test...
dpkg-deb: warning: parsing file 'epm-4.3-linux-3.16-x86_64/DEBIAN/control' near line 4 package 'epm':
 'x86_64' is not a valid architecture name: character `_' not allowed (only letters, digits and characters `-')
dpkg-deb: warning: ignoring 1 warning about the control file(s)
dpkg-deb: warning: parsing file 'epm-documentation-4.3-linux-3.16-x86_64/DEBIAN/control' near line 4 package 'epm-documentation':
 'x86_64' is not a valid architecture name: character `_' not allowed (only letters, digits and characters `-')
dpkg-deb: warning: ignoring 1 warning about the control file(s)
dpkg-deb: warning: parsing file 'epm-man-4.3-linux-3.16-x86_64/DEBIAN/control' near line 4 package 'epm-man':
 'x86_64' is not a valid architecture name: character `_' not allowed (only letters, digits and characters `-')
dpkg-deb: warning: ignoring 1 warning about the control file(s)
Native distribution build test PASSED.

I'm not sure if that's an issue at all, however this should hopefully be a simple patch as in #295.

Cheers

Rawiri

**Comment by cpatrick08** [comment]
same from git build of epm on Ubuntu 17.04

**Comment by michaelrsweet** [comment]
OK, so this *was* partially fixed in EPM 4.3 (2 years ago) in commit 3d1d2c5c049ccf69149312d78140b6384ea7ba2b, but it looks like I missed the corresponding change when writing the control file...

**Comment by michaelrsweet** [comment]
[master 94a0d91] Really fix 64-bit Intel packages on Debian (Issue #48)
