### ISSUE TITLE
removal of symlinks fail when target is removed first

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/epm#51]
Version: -current
Original reporter: Bill Janssen

I'm seeing a lot of messages in my log like this:

epm: Unable to stat "/vagrant/goodstuff/Package/opt/goodstuff/bin/easy_install-2.7": No such file or directory
epm: Unable to remove "/vagrant/goodstuff/Package/opt/goodstuff/bin": Directory not empty
ESP Package Manager v4.3
Copyright 1999-2007 by Easy Software Products.
... and so forth ...

This winds up leaving lots of packaging junk lying around.  easy_install-2.7 is a symlink to easy_install, which gets removed first.  Perhaps 'lstat' instead of 'stat'?

**Comment by michaelrsweet** [comment]
[master 7e6a771] Fix unlink_directory with symlinks (Issue #51)

**Comment by janssen** [comment]
Thanks.
