### ISSUE TITLE
EPM v 4.3 generate incomplete rpm spec file

### ISSUE THREAD

**Issue by andretux** [michaelrsweet/epm#53]
I use the same list file that I use with EPM v 4.2 and v 4.3 adds the directories to the spec file and in some cases one file in the directory but with most no files.

I use wildcards in the list file.

For instance:
d $bin_perm $def_owner $def_grp $dst_web/lib/PHPExcel/locale -
f $web_perm $def_owner $def_grp $dst_web/lib/PHPExcel/locale $src_web/lib/PHPExcel/locale/* 
d $bin_perm $def_owner $def_grp $dst_web/lib/PHPExcel/locale/da -
f $web_perm $def_owner $def_grp $dst_web/lib/PHPExcel/locale/da $src_web/lib/PHPExcel/locale/da/*

**Comment by michaelrsweet** [comment]
Try running epm with the -k option and attach the generated spec file along with the list file.

**Comment by andretux** [comment]
Ok, here is the list file and the spec files generated by epm 4.2 and 4.3

[epm_problems.zip](https://github.com/michaelrsweet/epm/files/1132793/epm_problems.zip)

**Comment by mwibeck** [comment]
Wildcards were destroyed in commit e0d55452f6bf16318f05ab1f0153f4a748e7a6bb.
dist.c: line 1111:
strlcpy(temp, dent->d_name, sizeof(temp));

temp is a char *.

So, only files with names shorter than the pointer size (4 or 8 bytes) will ever get copied.
Working on a pull request.

**Comment by michaelrsweet** [comment]
Fixed in both master and branch-4 (for 4.x).

Not sure right now when I will do an updated release..
