### ISSUE TITLE
deb x86_64 isn't amd64 git build Ubuntu 17.10

### ISSUE THREAD

**Issue by cpatrick08** [michaelrsweet/epm#58]
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 4 package 'cups:x86_64':
 'x86_64' is not a valid architecture name: character '_' not allowed (only letters, digits and characters '-')
dpkg: error processing archive cups-2.2.5-linux-4.12-x86_64.deb (--install):
 package architecture (x86_64) does not match system (amd64)

**Comment by michaelrsweet** [comment]
This is issue #48 ...
