### ISSUE TITLE
RPM packages not building

### ISSUE THREAD

**Issue by IceTony** [michaelrsweet/epm#70]
Hello!
I'm trying to building rpm package with default epm.list:
```
#
# Sample software list file for the ESP Package Manager (EPM).
#
# Copyright 1999-2017 by Michael R Sweet
# Copyright 1999-2007 by Easy Software Products, all rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

# Directories...
$prefix=/usr/local
$exec_prefix=/usr/local
$bindir=${exec_prefix}/bin
$datarootdir=/usr/local/share
$datadir=/usr/local/share
$docdir=${datadir}/doc/epm
$libdir=/usr/local/lib
$mandir=${datarootdir}/man
$srcdir=.

# Product information
%product ESP Package Manager
%copyright 1999-2017 by Michael R Sweet, All Rights Reserved.
%vendor Easy Software Products
%license ${srcdir}/COPYING
%readme ${srcdir}/README.md
%description Universal software packaging tool for UNIX.
%version 4.4.1 441

# Executables
%system all
f 0555 root sys ${bindir}/epm epm
f 0555 root sys ${bindir}/epminstall epminstall
f 0555 root sys ${bindir}/mkepmlist mkepmlist

# Documentation
%subpackage documentation
%description Documentation
f 0444 root sys ${docdir}/README $srcdir/README.md
f 0444 root sys ${docdir}/COPYING $srcdir/COPYING
f 0444 root sys ${docdir}/epm-book.html $srcdir/doc/epm-book.html

# Man pages
%subpackage man
%description Man pages
f 0444 root sys ${mandir}/man1/epm.1 $srcdir/doc/epm.man
f 0444 root sys ${mandir}/man1/epminstall.1 $srcdir/doc/epminstall.man
f 0444 root sys ${mandir}/man1/mkepmlist.1 $srcdir/doc/mkepmlist.man
f 0444 root sys ${mandir}/man5/epm.list.5 $srcdir/doc/epm.list.man

# GUI files...
$GUIS=

%if GUIS
%subpackage
f 0555 root sys ${libdir}/epm/setup setup
f 0555 root sys ${libdir}/epm/uninst uninst

%system darwin
f 0444 root sys ${datadir}/epm/default.icns default.icns
%system all

%subpackage man
f 0444 root sys ${mandir}/man1/setup.1 $srcdir/doc/setup.man
f 0444 root sys ${mandir}/man5/setup.types.5 $srcdir/doc/setup.types.man

%endif
```
```
# ./epm -f rpm epm
```
but getting an error: `Packaging failed!`  
build in docker container `centos:7` with `yum install gcc rpm-build rpm-devel rpmlint make python bash coreutils diffutils patch rpmdevtools`

**Comment by michaelrsweet** [comment]
@IceTony Add the "-v" option to get more output about the cause of the failure.

**Comment by msaravanan77** [comment]
# cat bar.list
%product Kung Foo Firewall
%copyright 1999-2005 by Foo Industries, All Rights Reserved.
%vendor Foo Industries
%license COPYING
%readme README
%description Kung Foo firewall software for your firewall.
%version 1.2.3p4 1020304
f 0755 root root /tmp /tmp/delete/myfile

# epm -v -f rpm foo bar.list
ESP Package Manager v4.4
Copyright 1999-2017 by Michael R Sweet.

EPM is free software and comes with ABSOLUTELY NO WARRANTY; for details
see the GNU General Public License in the file COPYING or at
"http://www.fsf.org/gpl.html".  Report all problems to
"https://github.com/michaelrsweet/epm/issues".

Searching for product information...
Stripping executables in distribution...
Creating RPM distribution...
Creating spec file...
Copying temporary distribution files...
Building RPM binary distribution...
Packaging failed!

**Comment by michaelrsweet** [comment]
@msaravanan77  I can't reproduce in the current Git code - can you retry please?

**Comment by lhondareyte** [comment]
> # cat bar.list
> 
> %product Kung Foo Firewall
> %copyright 1999-2005 by Foo Industries, All Rights Reserved.
> %vendor Foo Industries
> %license COPYING
> %readme README
> %description Kung Foo firewall software for your firewall.
> %version 1.2.3p4 1020304
> f 0755 root root /tmp /tmp/delete/myfile

Destination for `/tmp/delete/myfile` is a directory (`/tmp`). This should be a file.
Replacing `/tmp/` with a filename (eg. `/tmp/foo`) works for me

**Comment by michaelrsweet** [comment]
Ah, OK, didn't notice that but yes you need to specify the full destination path when not using wildcards.
