### ISSUE TITLE
De-hardwire file modes.

### ISSUE THREAD

**Issue by MichaelTiernan** [michaelrsweet/epm#71]
I'd like to suggest that the current file mode settings in the project be changed to build packages in a more controlled setting...

When I'm building a package for distribution, I *do not* want anything in the workspace to be accessable by anyone else, my default modes are what I want (for my own reasons). The *package* that I distribute, when I distribute it, will have more open modes but while putting things together, it's not needed.

Example:
| Source | Example
|---|---
| deb.c: | mkdir(filename, 0777);
| epm.c: | make_directory(directory, 0777, getuid(), getgid());
| macos.c: | make_directory(filename, 0777, 0, 0);
| macos.c: | make_directory(pkgdir, 0777, 0, 0);
| portable.c: | mkdir(filename, 0777);
| rpm.c: | make_directory(filename, 0777, getuid(), getgid());
| setld.c: | mkdir(filename, 0777);
| swinstall.c: | mkdir(filename, 0777);

All those instances of "777" should be replaced by a settable variable. My `Development settings` Should apply to the files I create resulting in a packaged "product".

If you wanted to "ease into it", the wide open settings you currently use can be left as is unless a new environment variable is used or maybe configured at `configure` time.

Thank you for your time and software.

**Comment by michaelrsweet** [comment]
Your umask setting will reduce the 777 to whatever you want. And for RPM and Debian packages the permissions in the build root are the ones that show up in the package (so in those cases we need to enforce the permissions after making the directories...)

I’ll make sure I’m not unnecessarily leaving things wide open, but this is the first complaint I’ve seen in 25 years...

**Comment by MichaelTiernan** [comment]
Thanks for listening. Actually, it seems to not be working "as expected" for me. So, as far as I'm concerned, this is still me trying to understand why, not my saying it's an outright bug.

When I build an RPM package, my umask is 0077 (yes, tight) and then the output package/directory is ./linux_xxxxxxx/ and the modes on it are 0777.

For my own edification, I just wrapped all the '777' mode instances with an ifdef like this:

```
   533  #ifdef MCT
   534    make_directory(directory, 0000, getuid(), getgid());
   535  #else
   536    make_directory(directory, 0777, getuid(), getgid());
   537  #endif
```

To see what happens. When I do this, the modes on the created directory are 0700 for sure.

I've seen this for a long time and never said anything, it's just recently I thought I'd say something.

**Comment by michaelrsweet** [comment]
OK, just got a chance to look at the code, and the `make_directory` function sets the permissions exactly as shown when mode is not 0, otherwise it just lets the umask override the default mode 0755. The mkdir calls all seem to just allow umask to do its job.

I'll do a sweep tomorrow to make sure we are not forcing mode 0777 unnecessarily and maybe look at obsoleting some of the older package formats for "dead" operating systems while I'm at it...

**Comment by michaelrsweet** [comment]
[master ffdd43c] Fix some over-zealous permissions on temporary build directories (Issue #71)
