### ISSUE TITLE
Error in creating book(s) for epm. Cannot build mantohtml

### ISSUE THREAD

**Issue by MichaelTiernan** [michaelrsweet/epm#72]
The mantohtml.c file has two private includes in it:

```
#include <cups/string-private.h>
#include <cups/array-private.h>
```

Which aren't included in the distribution. (Yes I'll go grab the cups source for this file.)

**Comment by michaelrsweet** [comment]
Hmm, weird, not sure why those are being included. I have a newer version of this code that doesn't use any CUPS headers anyways so maybe I can just replace it...

**Comment by michaelrsweet** [comment]
OK, I just pushed a fix.
