### ISSUE TITLE
Documentation question/possible issue.

### ISSUE THREAD

**Issue by MichaelTiernan** [michaelrsweet/epm#74]
While reading the docs, I came across this and it stuck out to me. I thought it might be something you'd want to hear in an effort to clarify for new users.

____

In the manpage for epm(1) there's a flag listed as:
`-s setup.ext`
and later is a flag for
`--setup-image setup.ext`

It seems like the first might be a "left-over" or belongs with the second one or something since there's no explaination for it.

Here's a slice of that page...
~~~
[...]
   includes the operating system name.

   -s setup.ext

[...]
   --setup-image setup.ext
   Include the ESP Software Wizard with the specified image file with the
   distribution. This option is currently only supported by portable
   distributions.
[...]
~~~

**Comment by michaelrsweet** [comment]
[master f96f180] Fix documentation for old "-s" option (Issue #74)
