### ISSUE TITLE
Quirk in doc creation.

### ISSUE THREAD

**Issue by MichaelTiernan** [michaelrsweet/epm#75]
Again, just trying to he helpful.
___
I just noticed that my `./configure` run, didn't find the tool for htmldoc (I don't have it installed yet) but ran on without dealing with it.

Here's what I mean, first the config then an attempt at making docs.

~~~
[mtiernan@]{ESP_Package_Manager}$ ./configure
[...]
checking for gzip... /sw/bin/gzip
checking for htmldoc... no
checking for mkdir... /bin/mkdir
[...]
configure: creating ./config.status
config.status: creating Makefile
config.status: creating epm.list
config.status: creating doc/Makefile
[...]
~~~
Now requesting the docs get made...
~~~
[mtiernan@]{doc}$ cd doc
[mtiernan@]{doc}$ make all
batch epm-book.book --titleimage title.png -f epm-book.epub
batch: garbled time
make: [epm-book.epub] Error 1 (ignored)
batch epm-book.book --size universal -f epm-book.pdf
batch: garbled time
make: [epm-book.pdf] Error 1 (ignored)
~~~

In my opinion, if htmldoc isn't found, there should be two choices:
1. Stop and require a flag stating 'no-htmldoc' or something so that the doc makes don't fail.
1. Subsitute the equivilant of a 'no-op' such as `/bin/false` for the command so that the doc makes don't completely fail.

The problem being that without a value for `htmldoc` in the makefile, it tries to excute the rest of the make line which is "--batch ...." which gets interpeted by the system as a call to the batch subsystem.
___
Thank you for your time.

**Comment by michaelrsweet** [comment]
[master 6eabf6d] Fix some build system issues (Issue #75, Issue #76)
