### ISSUE TITLE
Question from docs... (Last one! I promise.)

### ISSUE THREAD

**Issue by MichaelTiernan** [michaelrsweet/epm#77]
So I was reviewing section 3 of the book and found a spot that I had to read over again a couple of times to clarify it and I thought I'd offer it as feedback where someone might find it confusing if they're new(ish) to EPM.

___
<h1>In Document '3-Packaging':</h1>                                                                                                      

[  Huge chunk cut for discussion.... ]

---

<PRE>
d 755 root sys /var/spool/foo -
</PRE>                         

<P>Finally, symbolic links use the letter <CODE>l</CODE> (lowercase L) for the type field:</P>

<PRE>
l 000 root sys /usr/bin/foobar foo
</PRE>                            

<P>The source field specifies the file to link to and can be a relative path.</P>
<hr>                                                                             
<ul>                                                                             
Question that arises when reading this...                                        
<br>                                                                             
What frame of reference do we use for 'foo'?                                     
Is it 'foo' when the package is built or 'foo' when the package is being installed?
<br>                                                                               
I'm of the opinion that the doc should clarify that statement including, if it's the second choice above, then where's that 'foo' live? What path is it grabbing it from? Relative to what?
<br>
<i>Yes, I'm aware that with lots of experience this becomes much more clear but until then we're confused.</i>
</ul>

---

<H3>Wildcards</H3>

<P>Wildcard patterns can be used in the source field to include multiple
files on a single line:

<PRE>
f 0444 root sys /usr/share/doc/foo *.html
</PRE>

<hr>
<ul>
<p>
This is actually not clear to me.
Even with my experience using EPM, I find it hard to read.
Does this say "Any 'html' file you find install it as '/usr/share/doc/foo'" (Which makes no sense, many to one.) <i>OR</i>
Does it say "In the directory 'foo' under '/usr/share/doc' create a link for every 'html' file in our current path?"
(Which is what I assume.)
<p>
I would request a little more verbiage on this.
<p>
It might be sufficient to clarify it with a line above that saying
<pre>"d 0555 root sys /usr/share/doc/foo -"</pre>
to make it clearer about what's being created but I'm not sure yet.
</ul>

Thank you for your indulgence.

**Comment by michaelrsweet** [comment]
@MichaelTiernan I'll make some clarifications. FYI:

- For symlinks, relative paths are relative to the destination, just as if you typed "ln -s foo /path/to/bar"

- For wildcards, the files go in /usr/share/doc/foo/*filename.html*; I'll expand the example to show this explicitly.

**Comment by michaelrsweet** [comment]
[master 0dda975] Update symlink and wildcard discriptions (Issue #77)
