### ISSUE TITLE
Disable automatic dependencies with RPM format

### ISSUE THREAD

**Issue by lhondareyte** [michaelrsweet/epm#79]
Hi,
To disable automatic dependencies with RPM format, we need to add "AutoReqProv: no" in SPEC file. How can it be done via EPM? And in general, is there a way to add a specific directive to the SPEC file generated by epm?
Regards,
Luc

**Comment by michaelrsweet** [comment]
The EPM book provides an example of this in chapter 4:

```
%literal(spec) <<EOF
%changelog
* Tue Aug 26 2008 John Doe <johndoe@domain.com>

- Added new feature "bar"

* Fri Aug 1 2008 John Doe <johndoe@domain.com>

- Added new feature "foo"
EOF
```

So for your case try:

```
%literal(spec) <<EOF
AutoReqProv: no
EOF
```

or just:

```
%literal(spec) AutoReqProv: no
```

since it is a single line.

**Comment by lhondareyte** [comment]
It works. Thanks a lot
