### ISSUE TITLE
epm 4.5 can't make on solaris 11.4 for sparc

### ISSUE THREAD

**Issue by liuqiong7618** [michaelrsweet/epm#83]
Hello:
When I make the epm 4.5 on solaris 11.4 for sparc, it pop up an error as below:

/usr/lib/sparcv9/libfltk_images.a
/usr/lib/sparc9/libftk.a
No such file or directory

How Can I fix this issue

**Comment by michaelrsweet** [comment]
Either configure EPM without the GUI (--disable-gui) or reinstall FLTK on your system.
