### ISSUE TITLE
make: INSTALL@: Command not found

### ISSUE THREAD

**Issue by 309441166** [michaelrsweet/epm#84]
make: INSTALL@: Command not found

**Comment by michaelrsweet** [comment]
What version of EPM are your using?

**Comment by OneTop4458** [comment]
I have the same symptom and it is shown below.

`
root@earth:/tmp/epm-4.5# make install
Installing EPM setup/uninst in /usr/local/lib/epm
make: INSTALL@: Command not found
make: *** [install-guis] Error 127
`

**Comment by michaelrsweet** [comment]
[master 694db43] Fix @INSTALL@ macro (Issue #84)
