### ISSUE TITLE
Problem with postinst script in Ubuntu OS

### ISSUE THREAD

**Issue by OneTop4458** [michaelrsweet/epm#85]
After creating deb packages using epm,
The following warning occurs during installation
![image](https://user-images.githubusercontent.com/40881444/89870153-6452bf80-dbf0-11ea-9dcb-1b4d75b1b9a2.png)

Therefore, when you open the file in the path below, the contents are as follows:
var/lib/dpkg/info/####.Postinst
![image](https://user-images.githubusercontent.com/40881444/89870446-d0352800-dbf0-11ea-9911-6398029d810d.png)

The Run Level part seems to be strange and identified by the code as the next part.
![image](https://user-images.githubusercontent.com/40881444/89869770-cbbc3f80-dbef-11ea-9a31-d6d828425d17.png)

The problem with the script
An error occurred in the Ubuntu 16.04 64Bit environment that cannot be reinstalled

root@(hostname)[/usr/Security/src]dpkg --remove --force-remove-reinstreq Package Name
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package is in a very bad inconsistent state; you should
reinstall it before attempting a removal
(Reading database ... 122809 files and directories currently installed.)
Removing Package Name (2.2.2) ...
Cannot find Package Name installation, exiting...
dpkg: error processing package Package Name (--remove):
subprocess installed pre-removal script returned error exit status 2
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: start runlevel arguments (2 3 4 5) do not match Package Name-agent Default-Start values (3 5)
update-rc.d: warning: stop runlevel arguments (0) do not match Package Name-agent Default-Stop values (none)
insserv: warning: script 'K01postgresql-9.5' missing LSB tags and overrides
insserv: warning: script 'K01acronis_schedule' missing LSB tags and overrides
insserv: warning: script 'postgresql-9.5' missing LSB tags and overrides
insserv: warning: script 'acronis_schedule' missing LSB tags and overrides
Cannot find Package Name installation, exiting...
dpkg: error while cleaning up:
subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
Package Name

root@(Hostname)[/usr/Security/src] uname -a
Linux (Hostname) 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@(Hostname)[/usr/Security/src]cat /proc/version
Linux version 4.4.0-154-generic (buildd@lgw01-amd64-049) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) ) #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019

**Comment by michaelrsweet** [comment]
[master 97da900] Fix debian packages - rc-update.d no longer supports start/stop commands (Issue #85)
